### ISSUE TITLE
ビューを作って，Swipeで遷移できるようにする

### ISSUE THREAD

**Issue by tail12** [ccm-koakuma/uni_fes_android#1]
@babyshoma
# WHAT
今回のアプリでは，一つのタブの中をスワイプで遷移できるようにするという機能をつける．
そこで，まずは，スワイプでページ切り替えの方法を理解してもらう．

実装する理由として，
Android のDevelopersサイトでも，スクリーンマップ内の兄弟関係のブラウズにはベストプラクティスとして Lateral Navigation が推奨されているため．
[Creating Swipe Views with Tabs](https://developer.android.com/training/implementing-navigation/lateral.html)

**Comment by stealpattan** [comment]
できた。けど、コミットで指定するん忘れた。
