### ISSUE TITLE
デザイン通りにUIパーツを置く

### ISSUE THREAD

**Issue by tail12** [ccm-koakuma/uni_fes_android#3]
# WHAT
デザインができ次第，
1. 実際にUIパーツをおいてみる(機能は実装しなくてもいい)
2. 画面遷移できるようにする

その他のリクエストの取得などは今回のissueでは求めない．

**Comment by stealpattan** [comment]
デザイン：https://prottapp.com/p/1e39c0#/s/59b67a8886e4655a6b447554
